apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ironveil
data:
  SERVICE_NAME: backend
  NODE_ENV: production
  LOG_LEVEL: info
  PORT: "3000"
  KAFKA_BROKERS: kafka:9092
  AI_SERVICE_URL: http://ai-service:3003
  SIMULATOR_URL: http://sensor-simulator:3002
  FRONTEND_URL: http://frontend:80