apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ironveil
type: Opaque
stringData:
  DATABASE_URL: postgresql://ironveil:ironveil_dev_password@postgres:5432/ironveil
  REDIS_URL: redis://:ironveil_dev_password@redis:6379
  JWT_SECRET: 81ebd56667291d016c4434754dfad5d370a08a17634f1de7b225a87b56731a0f